### ISSUE TITLE
README example could benefit from phrase_from_file/2

### ISSUE THREAD

**Issue by triska** [aarroyoc/marquete#1]
Both Scryer and Trealla support `phrase_from_file/2` to read an entire file at once. For instance:

<pre>
<b>?- phrase_from_file(seq(Cs), "README.md").</b>
</pre>

yields the string `Cs` with all characters of `README.md`. A key advantage of this solution is that `phrase_from_file/2` also automatically closes the file and frees the stream handle in case of any errors. `open/3` should always be wrapped in `setup_call_cleanup/3`.

**Comment by aarroyoc** [comment]
Thanks! I've updated the README in https://github.com/aarroyoc/marquete/commit/9057321dfe91dbbac7f4d567afbeb4e7f58f5820. Also using `phrase_to_file/2`
